{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "435abd88-25e6-468e-bbf4-dc2bba6fb5c9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# utils/charts.py\n",
    "\n",
    "import plotly.graph_objects as go\n",
    "import pandas as pd\n",
    "\n",
    "def plot_gauge_chart(value):\n",
    "    \"\"\"Creates a gauge chart for the risk score.\"\"\"\n",
    "    fig = go.Figure(go.Indicator(\n",
    "        mode=\"gauge+number\",\n",
    "        value=value,\n",
    "        domain={'x': [0, 1], 'y': [0, 1]},\n",
    "        title={'text': \"Risk Score\", 'font': {'size': 24}},\n",
    "        gauge={\n",
    "            'axis': {'range': [None, 100], 'tickwidth': 1, 'tickcolor': \"darkblue\"},\n",
    "            'bar': {'color': \"darkblue\"},\n",
    "            'bgcolor': \"white\",\n",
    "            'borderwidth': 2,\n",
    "            'bordercolor': \"gray\",\n",
    "            'steps': [\n",
    "                {'range': [0, 30], 'color': 'green'},\n",
    "                {'range': [30, 70], 'color': 'orange'},\n",
    "                {'range': [70, 100], 'color': 'red'}],\n",
    "            'threshold': {\n",
    "                'line': {'color': \"black\", 'width': 4},\n",
    "                'thickness': 0.75,\n",
    "                'value': value}}))\n",
    "    fig.update_layout(height=250, margin=dict(l=10, r=10, t=40, b=10))\n",
    "    return fig\n",
    "\n",
    "def plot_radar_chart(patient_data, avg_data):\n",
    "    \"\"\"Creates a radar chart comparing patient values to averages.\"\"\"\n",
    "    categories = list(avg_data.keys())\n",
    "    patient_values = list(patient_data.values())\n",
    "    avg_values = list(avg_data.values())\n",
    "    \n",
    "    fig = go.Figure()\n",
    "\n",
    "    fig.add_trace(go.Scatterpolar(\n",
    "        r=patient_values,\n",
    "        theta=categories,\n",
    "        fill='toself',\n",
    "        name='Patient Values'\n",
    "    ))\n",
    "    fig.add_trace(go.Scatterpolar(\n",
    "        r=avg_values,\n",
    "        theta=categories,\n",
    "        fill='toself',\n",
    "        name='Population Averages'\n",
    "    ))\n",
    "\n",
    "    fig.update_layout(\n",
    "        polar=dict(\n",
    "            radialaxis=dict(\n",
    "                visible=True,\n",
    "                range=[0, max(max(patient_values), max(avg_values)) * 1.1]\n",
    "            )),\n",
    "        showlegend=True,\n",
    "        title=\"Patient Profile vs. Averages\"\n",
    "    )\n",
    "    return fig\n",
    "    \n",
    "def plot_shap_explanation(shap_values, feature_names):\n",
    "    \"\"\"Creates a waterfall chart for SHAP values.\"\"\"\n",
    "    base_value = shap_values.base_values\n",
    "    \n",
    "    fig = go.Figure(go.Waterfall(\n",
    "        name=\"Prediction\",\n",
    "        orientation=\"h\",\n",
    "        measure=[\"relative\"] * len(feature_names),\n",
    "        y=feature_names,\n",
    "        x=shap_values.values,\n",
    "        connector={\"line\": {\"color\": \"rgb(63, 63, 63)\"}},\n",
    "        base=base_value\n",
    "    ))\n",
    "\n",
    "    fig.update_layout(\n",
    "        title=\"Prediction Explainability (SHAP Values)\",\n",
    "        showlegend=False,\n",
    "        yaxis_title=\"Features\",\n",
    "        xaxis_title=\"Contribution to Prediction\"\n",
    "    )\n",
    "    return fig"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
